import Head from "next/head";
import Header from "@/components/Header/Header";
import Navbar from "@/components/Navbar/Navbar";
import {useLoading} from "@/context/useLoading";
import {Backdrop, CircularProgress} from "@mui/material";

const MainLayout = ({title = 'Escobar', sections, children}) => {
    const {loading, setLoading} = useLoading();

    return (
        <>
            <Head>
                <title>{title}</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
            </Head>

            {/*LOADER*/}
            <Backdrop
                sx={{ color: '#fff', zIndex: (theme) => theme.zIndex.drawer + 1000000}}
                open={loading}
            >
                <CircularProgress color="inherit" />
            </Backdrop>

            <div className="wrapper">
                <Header />
                <Navbar />
                <main>
                    {children}
                </main>
            </div>
        </>
    );
};

export default MainLayout;